
package com.example.oldCompanySystem.Entity.PersonnelEntity;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PersonnelDoesNotExistFault", targetNamespace = "http://www.oldCompany.com/fault")
public class PersonnelDoesNotExistFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PersonnelDoesNotExistFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PersonnelDoesNotExistFault(String message, PersonnelDoesNotExistFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PersonnelDoesNotExistFault(String message, PersonnelDoesNotExistFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: PersonnelEntity.PersonnelDoesNotExistFaultType
     */
    public PersonnelDoesNotExistFaultType getFaultInfo() {
        return faultInfo;
    }

}
