
package com.example.oldCompanySystem.Entity.OrderEntity;

import com.example.oldCompanySystem.bl.OrderPort;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderService", targetNamespace = "http://www.oldSystem.com/wsdl", wsdlLocation = "file:/C:/Users/82582/Desktop/\u5b9e\u8df5\u8bfe/oldSystem/xml/wsdl/OrderManage.wsdl")
public class OrderService
    extends Service
{

    private final static URL ORDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDERSERVICE_EXCEPTION;
    private final static QName ORDERSERVICE_QNAME = new QName("http://www.oldSystem.com/wsdl", "OrderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/82582/Desktop/\u5b9e\u8df5\u8bfe/oldSystem/xml/wsdl/OrderManage.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERSERVICE_WSDL_LOCATION = url;
        ORDERSERVICE_EXCEPTION = e;
    }

    public OrderService() {
        super(__getWsdlLocation(), ORDERSERVICE_QNAME);
    }

    public OrderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERSERVICE_QNAME, features);
    }

    public OrderService(URL wsdlLocation) {
        super(wsdlLocation, ORDERSERVICE_QNAME);
    }

    public OrderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERSERVICE_QNAME, features);
    }

    public OrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderPort
     */
    @WebEndpoint(name = "OrderPort")
    public OrderPort getOrderPort() {
        return super.getPort(new QName("http://www.oldSystem.com/wsdl", "OrderPort"), OrderPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderPort
     */
    @WebEndpoint(name = "OrderPort")
    public OrderPort getOrderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oldSystem.com/wsdl", "OrderPort"), OrderPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERSERVICE_EXCEPTION!= null) {
            throw ORDERSERVICE_EXCEPTION;
        }
        return ORDERSERVICE_WSDL_LOCATION;
    }

}
